# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'DropDownDemo' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for DropDownDemo
  	pod 'PNDropDown', :path => "../PNDropDown/"
end
